//! Rust code generation.

use crate::schema::{FieldDef, FieldType, MessageDef, Schema};

/// Generate Rust code from a schema.
pub fn generate(schema: &Schema) -> String {
    let mut output = String::new();

    // Header
    output.push_str("//! Auto-generated by uproto. Do not edit.\n\n");
    output.push_str("use serde::{Deserialize, Serialize};\n\n");

    // Generate structs
    for msg in &schema.messages {
        output.push_str(&generate_struct(msg));
        output.push('\n');
    }

    // Generate enum
    output.push_str(&generate_enum(schema));

    output
}

fn generate_struct(msg: &MessageDef) -> String {
    let mut s = String::new();

    if let Some(desc) = &msg.description {
        s.push_str(&format!("/// {}\n", desc));
    }

    s.push_str("#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]\n");
    s.push_str(&format!("pub struct {} {{\n", msg.name));

    for field in &msg.fields {
        s.push_str(&generate_field(field));
    }

    s.push_str("}\n");
    s
}

fn generate_field(field: &FieldDef) -> String {
    let rust_type = to_rust_type(&field.ty, !field.required);
    let name = to_snake_case(&field.name);

    let mut out = String::new();

    if !field.required {
        out.push_str("    #[serde(skip_serializing_if = \"Option::is_none\")]\n");
    }

    out.push_str(&format!("    pub {}: {},\n", name, rust_type));
    out
}

fn to_rust_type(ty: &FieldType, optional: bool) -> String {
    let base = match ty {
        FieldType::String => "String",
        FieldType::I8 => "i8",
        FieldType::I16 => "i16",
        FieldType::I32 => "i32",
        FieldType::I64 => "i64",
        FieldType::U8 => "u8",
        FieldType::U16 => "u16",
        FieldType::U32 => "u32",
        FieldType::U64 => "u64",
        FieldType::F32 => "f32",
        FieldType::F64 => "f64",
        FieldType::Bool => "bool",
    };

    if optional {
        format!("Option<{}>", base)
    } else {
        base.to_string()
    }
}

fn generate_enum(schema: &Schema) -> String {
    let mut s = String::new();

    s.push_str("/// Protocol message types.\n");
    s.push_str("#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]\n");
    s.push_str("#[serde(tag = \"type\")]\n");
    s.push_str("pub enum Message {\n");

    for msg in &schema.messages {
        s.push_str(&format!("    {}({}),\n", msg.name, msg.name));
    }

    s.push_str("}\n");
    s
}

fn to_snake_case(s: &str) -> String {
    let mut result = String::new();
    for (i, c) in s.chars().enumerate() {
        if c.is_uppercase() {
            if i > 0 {
                result.push('_');
            }
            result.push(c.to_lowercase().next().unwrap());
        } else {
            result.push(c);
        }
    }
    result
}
