//! TypeScript code generation.

use crate::schema::{FieldDef, FieldType, MessageDef, Schema};

/// Generate TypeScript code from a schema.
pub fn generate(schema: &Schema) -> String {
    let mut output = String::new();

    // Header
    output.push_str("// Auto-generated by uproto. Do not edit.\n\n");

    // Generate interfaces
    for msg in &schema.messages {
        output.push_str(&generate_interface(msg));
        output.push('\n');
    }

    // Generate union type
    output.push_str(&generate_union(schema));

    output
}

fn generate_interface(msg: &MessageDef) -> String {
    let mut s = String::new();

    if let Some(desc) = &msg.description {
        s.push_str(&format!("/** {} */\n", desc));
    }

    s.push_str(&format!("export interface {} {{\n", msg.name));

    for field in &msg.fields {
        s.push_str(&generate_property(field));
    }

    s.push_str("}\n");
    s
}

fn generate_property(field: &FieldDef) -> String {
    let ts_type = to_ts_type(&field.ty);
    let optional = if field.required { "" } else { "?" };

    format!("  {}{}: {};\n", field.name, optional, ts_type)
}

fn to_ts_type(ty: &FieldType) -> &'static str {
    match ty {
        FieldType::String => "string",
        FieldType::I8 | FieldType::I16 | FieldType::I32 | FieldType::I64 |
        FieldType::U8 | FieldType::U16 | FieldType::U32 | FieldType::U64 |
        FieldType::F32 | FieldType::F64 => "number",
        FieldType::Bool => "boolean",
    }
}

fn generate_union(schema: &Schema) -> String {
    let mut s = String::new();

    s.push_str("/** Protocol message types. */\n");
    s.push_str("export type Message =\n");

    for (i, msg) in schema.messages.iter().enumerate() {
        let sep = if i == schema.messages.len() - 1 { ";" } else { "" };
        s.push_str(&format!(
            "  | {{ type: \"{}\"; data: {} }}{}\n",
            msg.name, msg.name, sep
        ));
    }

    s
}
