//! Rust code generation.

use std::fs;
use std::io::Write;
use std::path::Path;

use crate::schema::{MessageDef, PropDef, Schema, ValueType};
use crate::Error;

/// Rust code generator.
pub struct RustCodeGen<'a> {
    schema: &'a Schema,
}

impl<'a> RustCodeGen<'a> {
    pub fn new(schema: &'a Schema) -> Self {
        Self { schema }
    }

    /// Generate Rust code as a string.
    pub fn generate(&self) -> String {
        let mut output = String::new();

        // Header
        output.push_str("//! Auto-generated by unison-protocol. Do not edit.\n\n");
        output.push_str("use serde::{Deserialize, Serialize};\n\n");

        // Generate structs for each message
        for msg in self.schema.messages.values() {
            output.push_str(&self.generate_struct(msg));
            output.push('\n');
        }

        // Generate enum for all messages
        output.push_str(&self.generate_enum());

        output
    }

    fn generate_struct(&self, msg: &MessageDef) -> String {
        let mut s = String::new();

        // Doc comment
        if let Some(desc) = &msg.description {
            s.push_str(&format!("/// {}\n", desc));
        }

        s.push_str("#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]\n");
        s.push_str(&format!("pub struct {} {{\n", msg.name));

        for prop in &msg.props {
            s.push_str(&self.generate_field(prop));
        }

        s.push_str("}\n");
        s
    }

    fn generate_field(&self, prop: &PropDef) -> String {
        let rust_type = self.to_rust_type(&prop.ty, !prop.required);

        let mut field = String::new();

        if let Some(desc) = &prop.description {
            field.push_str(&format!("    /// {}\n", desc));
        }

        // Add serde attributes for optional fields
        if !prop.required {
            field.push_str("    #[serde(skip_serializing_if = \"Option::is_none\")]\n");
        }

        field.push_str(&format!("    pub {}: {},\n", to_snake_case(&prop.name), rust_type));
        field
    }

    fn to_rust_type(&self, ty: &ValueType, optional: bool) -> String {
        let base = match ty {
            ValueType::String => "String".to_string(),
            ValueType::I8 => "i8".to_string(),
            ValueType::I16 => "i16".to_string(),
            ValueType::I32 => "i32".to_string(),
            ValueType::I64 => "i64".to_string(),
            ValueType::U8 => "u8".to_string(),
            ValueType::U16 => "u16".to_string(),
            ValueType::U32 => "u32".to_string(),
            ValueType::U64 => "u64".to_string(),
            ValueType::F32 => "f32".to_string(),
            ValueType::F64 => "f64".to_string(),
            ValueType::Bool => "bool".to_string(),
            ValueType::Optional(inner) => format!("Option<{}>", self.to_rust_type(inner, false)),
        };

        if optional && !matches!(ty, ValueType::Optional(_)) {
            format!("Option<{}>", base)
        } else {
            base
        }
    }

    fn generate_enum(&self) -> String {
        let mut s = String::new();

        s.push_str("/// Protocol message types.\n");
        s.push_str("#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]\n");
        s.push_str("#[serde(tag = \"type\")]\n");
        s.push_str("pub enum Message {\n");

        for name in self.schema.messages.keys() {
            s.push_str(&format!("    {}({}),\n", name, name));
        }

        s.push_str("}\n");
        s
    }

    /// Write generated code to a file.
    pub fn write_to(&self, path: impl AsRef<Path>) -> Result<(), Error> {
        let code = self.generate();
        let mut file = fs::File::create(path)?;
        file.write_all(code.as_bytes())?;
        Ok(())
    }
}

fn to_snake_case(s: &str) -> String {
    let mut result = String::new();
    for (i, c) in s.chars().enumerate() {
        if c.is_uppercase() {
            if i > 0 {
                result.push('_');
            }
            result.push(c.to_lowercase().next().unwrap());
        } else {
            result.push(c);
        }
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_rust() {
        let schema = Schema::parse(r#"
            message "Connect" {
                prop "client_id" type="string" required=#true
                prop "version" type="u32"
            }
        "#).unwrap();

        let code = RustCodeGen::new(&schema).generate();
        assert!(code.contains("pub struct Connect"));
        assert!(code.contains("pub client_id: String"));
        assert!(code.contains("pub version: Option<u32>"));
    }
}
