//! TypeScript code generation.

use std::fs;
use std::io::Write;
use std::path::Path;

use crate::schema::{MessageDef, PropDef, Schema, ValueType};
use crate::Error;

/// TypeScript code generator.
pub struct TypeScriptCodeGen<'a> {
    schema: &'a Schema,
}

impl<'a> TypeScriptCodeGen<'a> {
    pub fn new(schema: &'a Schema) -> Self {
        Self { schema }
    }

    /// Generate TypeScript code as a string.
    pub fn generate(&self) -> String {
        let mut output = String::new();

        // Header
        output.push_str("// Auto-generated by unison-protocol. Do not edit.\n\n");

        // Generate interfaces for each message
        for msg in self.schema.messages.values() {
            output.push_str(&self.generate_interface(msg));
            output.push('\n');
        }

        // Generate union type for all messages
        output.push_str(&self.generate_union_type());

        output
    }

    fn generate_interface(&self, msg: &MessageDef) -> String {
        let mut s = String::new();

        // Doc comment
        if let Some(desc) = &msg.description {
            s.push_str(&format!("/** {} */\n", desc));
        }

        s.push_str(&format!("export interface {} {{\n", msg.name));

        for prop in &msg.props {
            s.push_str(&self.generate_property(prop));
        }

        s.push_str("}\n");
        s
    }

    fn generate_property(&self, prop: &PropDef) -> String {
        let ts_type = self.to_ts_type(&prop.ty);
        let optional = if prop.required { "" } else { "?" };

        let mut field = String::new();

        if let Some(desc) = &prop.description {
            field.push_str(&format!("  /** {} */\n", desc));
        }

        field.push_str(&format!("  {}{}: {};\n", prop.name, optional, ts_type));
        field
    }

    fn to_ts_type(&self, ty: &ValueType) -> String {
        match ty {
            ValueType::String => "string".to_string(),
            ValueType::I8 | ValueType::I16 | ValueType::I32 | ValueType::I64 |
            ValueType::U8 | ValueType::U16 | ValueType::U32 | ValueType::U64 |
            ValueType::F32 | ValueType::F64 => "number".to_string(),
            ValueType::Bool => "boolean".to_string(),
            ValueType::Optional(inner) => format!("{} | null", self.to_ts_type(inner)),
        }
    }

    fn generate_union_type(&self) -> String {
        let mut s = String::new();

        s.push_str("/** Protocol message types. */\n");
        s.push_str("export type Message =\n");

        let names: Vec<_> = self.schema.messages.keys().collect();
        for (i, name) in names.iter().enumerate() {
            let sep = if i == names.len() - 1 { ";" } else { " |" };
            s.push_str(&format!("  | {{ type: \"{}\"; data: {} }}{}\n", name, name, sep));
        }

        s
    }

    /// Write generated code to a file.
    pub fn write_to(&self, path: impl AsRef<Path>) -> Result<(), Error> {
        let code = self.generate();
        let mut file = fs::File::create(path)?;
        file.write_all(code.as_bytes())?;
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_typescript() {
        let schema = Schema::parse(r#"
            message "Connect" {
                prop "client_id" type="string" required=#true
                prop "version" type="u32"
            }
        "#).unwrap();

        let code = TypeScriptCodeGen::new(&schema).generate();
        assert!(code.contains("export interface Connect"));
        assert!(code.contains("client_id: string"));
        assert!(code.contains("version?: number"));
    }
}
